### ISSUE TITLE
Request: downgrade google drive access request

### ISSUE THREAD

**Issue by ando-takahiro** [iY0Yi/ShaderBoy#1]
Thanks for providing such a nice app!

To make this cool app cooler, can you downgrade google drive access request?  Since I was requested all controls for my all files ;)

Anyway, Thanks again!

**Comment by iY0Yi** [comment]
I have changed the scope as follows.
```https://www.googleapis.com/auth/drive```
to: ```https://www.googleapis.com/auth/drive.file```
I think it works well. and became cooler :) Thanks!

**Comment by ando-takahiro** [comment]
Cool!

However, I can not see the commit on this repo, so I'm wondering if you actually have pushed that change...  Just in case let me remind that.

Anyway, thanks :)

**Comment by iY0Yi** [comment]
Sorry, I'm noob to GitHub ...
Here it is:
https://github.com/iY0Yi/ShaderBoy/commit/75fa545ab5cd109fecbd709c2e57efa96f6c7ec5
Thank you ;)

**Comment by ando-takahiro** [comment]
Perfect!  Thanks for your patience to hear my voice.

It perfectly worked as I wish.

<img width="603" alt="スクリーンショット 2019-05-21 13 43 39" src="https://user-images.githubusercontent.com/1460326/58068967-91234d00-7bce-11e9-8665-d1f8ac3f69df.png">

Thanks again!
