### ISSUE TITLE
ShaderBoy can no longer be invoked. / ShaderBoyが立ち上がらなくなりました。

### ISSUE THREAD

**Issue by gaziya** [iY0Yi/ShaderBoy#11]
昨日まで使えていたのですが、急にShaderBoyのロゴ画面で止まってしまい、それ以上進みません。Chrome のデベロッパーツールで確認したところ、
Failed to load resource: the server responded with a status of 403 ()
main.min.js:2 Uncaught (in promise) Object
と、なっています。
ロードの失敗のようなのですが対処法がわかりません。
よろしくお願いいたします。

**Comment by iY0Yi** [comment]
oAuth の問題でした。
たまーに起こるのですが、
Chrome の oAuth 削除後 → shaderboy.net から再認証。
で復帰できます。

参考：
http://nakamura001.hatenablog.com/entry/20130221/1361470381

It's an oAuth problem.
It happens sometimes.
If you [delete oAuth from Chrome](myaccount.google.com/permissions) and re-authenticate with [shaderboy.net](https://shaderboy.net/),
You can resume.

ref:
https://webapps.stackexchange.com/questions/30841/how-do-i-remove-permission-from-an-app-that-i-gave-google-oauth-access-to

**Comment by gaziya** [comment]
無事に復旧しました。ありがとうございます。
