### ISSUE TITLE
Application does not load

### ISSUE THREAD

**Issue by bettywolfy** [iY0Yi/ShaderBoy#34]
I'm using Opera for Android.
Every time I access shaderboy.net it gets a loading screen that never ends, which is a little suspicious.

**Comment by iY0Yi** [comment]
i cant reproduce it cause I dont have the env, but can you try super reloading?
how about on chrome?

**Comment by bettywolfy** [comment]
> i cant reproduce it cause I dont have the env, but can you try super reloading?
> how about on chrome?

I tried on Chrome, unfortunately the same thing happened.

**Comment by iY0Yi** [comment]
OK. Thank you. Could you give me your device/env info?

**Comment by iY0Yi** [comment]
I fixed a bug about loading assets.
I hope that it fixed your problem too.

**Comment by bettywolfy** [comment]
I discovered that the problem is with Opera for Android, sorry for the inconvenience, I'll close the discussion.
